apiVersion: v1
kind: ServiceAccount
metadata:
  name: civo-marketplace-grapple-solution-framework
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: grapple-solution-framework
subjects:
- kind: User
  name: civo-marketplace-grapple-solution-framework
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io